coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        only_pulls: true
    patch:
      default:
        target: auto
        threshold: 1%
        only_pulls: true
