language: node_js
node_js:
  - '14'

install:
  - npm install

script:
  - npm test
  - npm run lint
  - npm run build
  - npm run coverage

deploy:
  provider: npm
  cleanup: false
  edge: true
  api_token: $NPM_AUTH_TOKEN
  on:
    branch: master
    tags: true
